name: SonarQube scanner Python version

on: 
  workflow_call:
    inputs:
      python_version:
        required: true
      repos_name:
        required: true
        type: string
      path_requirements:
        type: string
        required: true
    secrets:
      SONAR_TOKEN:
          required: true
      SONAR_HOST_URL:
        required: true
      DISCORD_WEBHOOK:
        required: true


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '${{ inputs.python_version}}'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.path_requirements }}
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: On failure
      if: ${{ failure() }}
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: "{{ inputs.repos_name }}: @everyone Job it has failed for the SonarQube "
    - name: End SonarQube
      uses: Ilshidur/action-discord@0.3.2
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: "{{ inputs.repos_name }}: @everyone SonarQube has ended his scan check your project pelase "
          
